### ISSUE TITLE
Error using PopCorn.shows.get

### ISSUE THREAD

**Issue by Oiklo90** [nirewen/popcorn-api#5]
Hello. When i try to get shows informations using PopCorn.shows.get i always have an error, it has never worked (tried with movies and it's ok).
For example i try :
`PopCorn.shows.get({id: 'tt3322310'})
    .then(console.log)`
and i have this error :
`Uncaught (in promise) TypeError: Cannot read property 'push' of undefined
    at Show._patch (modules.js?hash=7b370d0e7fc4f5a8ba1a2c0ddc9b7aff4686a105:251591)
    at new Show (modules.js?hash=7b370d0e7fc4f5a8ba1a2c0ddc9b7aff4686a105:251449)
    at _rawDetails.then.value (modules.js?hash=7b370d0e7fc4f5a8ba1a2c0ddc9b7aff4686a105:251715)
    at meteor.js?hash=0504f43f667698535416b00eb44eb6f53161cb63:1223`

**Comment by nirewen** [comment]
You don't pass an object to the function, only the ID. Make sure you're using 1.1.0 because I've changed this lately

**Comment by Oiklo90** [comment]
i've installed the latest version on npm. i checked i have 1.1.0. what am i supposed to send to .shows.get?
I tried PopCorn.shows.get('tt3322310') i get the same error

**Comment by nirewen** [comment]
Oh I see the error!
Show is not being initialized with the episodes and seasons array.
I'll fix this in a bit. Thank you for reporting

**Comment by Oiklo90** [comment]
Ok thank you!!
